FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y python3 python3-pip
# RUN pip3 install pandas scikit-learn
# RUN apt-get clean

#  RUN mkdir -p data scripts modules
# COPY data/Iris.csv data
# RUN chmod -R 775 data
    
# COPY scripts/slice_data_final.py /scripts/
# COPY scripts/fit.py /scripts/
# RUN chmod -R 775 scripts
# COPY output/ /output/